config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:create, :show] do
    resources :lists, only: [:show]
  end

  resources :lists, only: [] do
    resources :items, only: [:create, :update]
  end

  resources :sessions, only: [:create]

  namespace :api, defaults: { format: :json } do
    resources :users do
      resources :lists
    end

    resources :lists, only: [] do
      resources :items, only: [:create, :update]
    end

    resources :items, only: [:destroy]
  end

  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in" => "sessions#new", as: "log_in"
  get "sign_up" => "users#new", as: "sign_up"
  root to: 'welcome#index'
end

app/models/item.rb
class Item < ActiveRecord::Base

  validates :description, presence: true

  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base

  validates :name, presence: true
  validates :permissions, presence: true, inclusion: { in: %w(private viewable open) }

  belongs_to :user
  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password

  validates :username, presence: true, uniqueness: true
  validates :password, confirmation: true, presence: true, on: :create

  has_many :lists, dependent: :destroy
  
  before_save :encrypt_password

  def self.authenticate(username, password)
    user = User.where(username: username).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApiController

  before_action :authenticated?

  def create
    item = Item.new(item_params)
    item.list = List.find(params[:list_id])
    if item.save
      render json: item
    else
      render json: { errors: item.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      render json: item
    else
      render json: { errors: item.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    begin
      item = Item.find(params[:id])
      item.destroy
      render json: {}, status: :no_content
    rescue ActiveRecord::RecordNotFound
      render json: {}, status: :not_found
    end
  end

  private

  def item_params
    params.require(:item).permit(:description, :complete)
  end
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApiController

  before_action :authenticated?

  def create
    list = List.new(list_params)
    list.user = User.find(params[:user_id])
    if list.save
      render json: list
    else
      render json: { errors: list.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    list = List.find(params[:id])
    if list.update(list_params)
      render json: list
    else
      render json: { errors: list.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    begin
      list = List.find(params[:id])
      list.destroy
      render json: {}, status: :no_content
    rescue ActiveRecord::RecordNotFound
      render json: {}, status: :not_found
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :permissions)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController

  before_action :authenticated?

  def index
    users = User.all
    render json: users, each_serializer: UserSerializer
  end

  def create
    user = User.new(user_params)
    if user.save
      render json: user
    else
      render json: { errors: user.errors.full_messages }, status: :unproccessable_entity
    end
  end

  def destroy
    begin
      user = User.find(params[:id])
      user.destroy
      render json: {}, status: :no_content
    rescue ActiveRecord::RecordNotFound
      render json: {}, status: :not_found
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  skip_before_action :verify_authenticity_token

  private

  def authenticated?
    authenticate_or_request_with_http_basic do |username, password|
      user = User.authenticate(username, password)
      if user.present?
        @current_user = user
        return true
      else
        return false
      end
    end
  end

  def password_hash(username, password)
    user = User.where(username: username).first
    BCrypt::Engine.hash_secret(password, user.password_salt)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def show
    @item = Item.find(params[:id])
  end

  def create
    item = Item.new(item_params)
    item.list = List.find(params[:list_id])
    if item.save
      flash[:notice] = "\"#{item.description}\" created successfully."
      redirect_to [item.list.user, item.list]
    else
      flash[:error] = "There was an error. Please try again."
      redirect_to [item.list.user, item.list]
    end
  end

  def update
    item = Item.find(params[:id])
    if item.update_attributes(item_params)
      flash[:notice] = "\"#{item.description}\" updated successfully."
      redirect_to [item.list.user, item.list]
    else
      flash[:error] = "There was an error. Please try again."
      redirect_to [item.list.user, item.list]
    end
  end

  private

  def item_params
    params.require(:item).permit(:description, :complete)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def show
    @list = List.find(params[:id])
    @item = Item.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      flash[:notice] = "Logged in!"
      redirect_to user
    else
      flash[:error] = "Invalid username or password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up."
      redirect_to @user
    else
      flash[:error] = "There was an error creating a user. Please try again."
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_item.html.erb
<li class="list-group-item">
  <%= item.description %>
  <span class="pull-right">
    <% if item.complete? %>
      Completed
    <% else %>
      <%= form_for [item.list, item], method: :put do |f| %>
        <%= f.hidden_field :complete, value: true %>
        <%= button_tag(type: 'submit', class: 'btn btn-success btn-xs') do %>
          <span class="glyphicon glyphicon-ok" ></span>
        <% end %>
      <% end %> 
    <% end %>
  </span>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpenTodoApi</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <% if current_user %>
        <li><%= link_to "My Todo lists", current_user %></li>
      <% end %>

      <div class="user-info pull-right">
        <% if current_user %>
          Logged in as <%= current_user.username %>.
          <%= link_to "Log out", log_out_path, class: 'btn btn-danger btn-sm' %>
        <% else %>
          <%= link_to "Log in", log_in_path, class: 'btn btn-primary btn-sm' %> or
          <%= link_to "Sign up", sign_up_path, class: 'btn btn-primary btn-sm' %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <br>

    <%= yield %>
  </div>
</body>
</html>

app/views/lists/_list.html.erb
<h3><%= link_to list.name, [current_user, list] %></h3>
<small><em><%= list.permissions %></em></small>

app/views/lists/show.html.erb
<h2 class="text-center"><%= @list.name %> Items</h2>

<div class="row">
  <div class="col-md-8">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title"><%= @list.name %></h4>
      </div>

      <ul class="list-group">
        <%= render partial: @list.items %>
        <li class="list-group-item">
          <%= form_for [@list, @item], class: 'form-inline' do |f| %>
            <div class="form-group">
              <%= f.text_field :description, class: 'form-control', placeholder: "Enter new item" %>
            </div>
            <%= f.submit "New", class: 'btn btn-success btn-sm' %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h2 class="text-center">Sign Up</h2>

<div class="row">
  <div class="col-md-8">

    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="form-group">
        <%= f.text_field :username, autofocus: true, class: 'form-control', placeholder: "Enter username" %>
      </div>

      <div class="form-group">
        <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
      </div>

      <div class="form-group">
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
      </div>

      <div class="form-group">
        <%= f.submit "Register", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h2 class="text-center"><%= current_user.username.capitalize %>'s Todo Lists</h2>

<div class="row">
  <div class="col-md-8">
    <%= render partial: current_user.lists %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Open Todo API</h1>
  <p>An externally usable API for basic todo list application.</p>
  <p>
    <%= link_to "Log In", log_in_path, class: 'btn btn-primary' %>
    or
    <%= link_to "Sign Up", sign_up_path, class: 'btn btn-primary' %>
  </p>
</div>

<div class="row text-center">
  <div class="col-md-4">
    <h2>Modify</h2>
    <p>user accounts and todo items from the command line.</p>
  </div>
  <div class="col-md-4">
    <h2>Simple</h2>
    <p>while remaining flexible to use.</p>
  </div>
  <div class="col-md-4">
    <h2>Support</h2>
    <p>other platforms and allow programmers to build on the tool.</p>
  </div>
</div>